bundling broadcast-channel
okta/okta-auth-js pull request #1299
Opened 2022-09-09 16:01 UTC by jaredperreault-okta

2022-09-09 16:25 UTC, shuowu-okta commented on README.md
> +> :warning: This option disables token lifetime validation, which can introduce security vulnerability issues. This option should be used for testing purpose. Please handle the error in your own app
seems like this change is brought from master, try rebase dev-7 against master and rebase this branch against dev-7

2022-09-09 16:25 UTC, shuowu-okta commented on scripts/build.js
> +delete packageJSON.dependencies['broadcast-channel'];
let's move `broadcast-channel` to devDeps, and delete the `devDependencies` field here

2022-09-09 21:29 UTC, shuowu approved these changes

2022-09-12 22:46 UTC, aarongranick-okta commented on rollup.config.js
> +      browser: true,
should "browser" be set based on the value of "env" ?

2022-09-12 22:50 UTC, aarongranick-okta requested changes
Please add a JIRA for removing workarounds for when/if broadcast-channel gets its issues sorted out. Please add comments in the code to indicate where we should remove workarounds.

2022-09-13 23:13 UTC, aarongranick-okta approved these changes

2022-10-17 14:14 UTC, closed without merging