doc: add sri to cdn script tag in readme
okta/okta-auth-js pull request #1498
Opened 2024-03-08 19:48 UTC by shuowu-okta

2024-03-11 21:31 UTC, lesterchoi-okta submitted a review, later dismissed
LGTM, up to you w.r.t. CLI API

2024-03-11 21:31 UTC, lesterchoi-okta commented on scripts/generate-sri.js
> +    throw new Error('--authjs-version is required');
nit: similar comment on mono PR re; CLI args vs flags = required vs optional

2024-03-11 21:56 UTC, jaredperreault-okta requested changes

2024-03-11 21:56 UTC, jaredperreault-okta commented on scripts/generate-sri.js
> +const { https } = require('follow-redirects');
Can this be accomplished without requiring an additional dependency?

2024-03-11 21:56 UTC, jaredperreault-okta commented on scripts/generate-sri.js
> +  await unpackArchive(artifactPath, UNPACK_DIR);
The fetching of the tar and unpacking could be more easily with
`npm i --prefix <dir> @okta/okta-auth-js@X.Y.Z`

2024-03-11 21:56 UTC, jaredperreault-okta commented on scripts/generate-sri.js
> +  const argv = yargs(hideBin(process.argv)).argv;
I don't think parsing `argv` for a single flag justifies introducing a new dependency

2024-03-13 16:22 UTC, shuowu-okta commented
Compared files from CDN and registry against v7.4.1, both are generated same sri

script used
```
const fileFromCdn = fs.readFileSync(path.join(ARTIFACTS, 'okta-auth-js-7.4.1-fromCdn.min.js'), { encoding: 'utf8' });
const fileFromPkg = fs.readFileSync(path.join(ARTIFACTS, 'okta-auth-js-7.4.1-fromPkg.min.js'), { encoding: 'utf8' });
const sriFromCdn = generateSri(fileFromCdn);
const sriFromPkg = generateSri(fileFromPkg);
console.info('generated same sri?', sriFromCdn === sriFromPkg);
```

console output:
```
shuo.wu@F7HMVX6KDM okta-auth-js % node ./scripts/generate-sri.js
Debugger attached.
generated same sri? true
```

@lesterchoi-okta @jaredperreault-okta

2024-03-14 20:07 UTC, shuowu-okta commented on README.md
> +<script src="https://global.oktacdn.com/okta-auth-js/7.5.1/okta-auth-js.polyfill.js" type="text/javascript" integrity="sha384-EBFsuVdi4TGp/DwS7b+t+wA8zmWK10omkX05ZjJWQhzWuW31t7FWEGOnHQeIr8+L" crossor
from cdn & yarn registry

2024-03-14 20:34 UTC, jaredperreault-okta approved these changes

2024-03-15 19:50 UTC, jaredperreault-okta commented on scripts/setup-e2e.sh
> +  export PUPPETEER_DOWNLOAD_BASE_URL="https://storage.googleapis.com/chrome-for-testing-public"
Is this still necessary?

2024-03-15 21:05 UTC, lesterchoi-okta reviewed
LGTM pending @jaredperreault-okta's comment re;  `PUPPETEER_DOWNLOAD_BASE_URL`

2024-03-18 17:56 UTC, jaredperreault-okta approved these changes

2024-03-18 18:11 UTC, merged